feat: add bootstrap_yay()

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -4,26 +4,44 @@
 # =                                    SETUP                                     =
 # ================================================================================
 
+set -euo pipefail
+
 choose_machine() {
     while true; do
         read -r -p "Select machine [wsl/pi]: " MACHINE
         case "$MACHINE" in
             wsl | pi) break ;;
-            *) echo "Invalid option." ;;
+            *) echo "Invalid option" ;;
         esac
     done
 }
 
 bootstrap_secrets() {
     while true; do
-        read -r -s -p "Enter your Restic password: " RESTIC_PASSWORD
-        read -r -s -p "Enter your B2 account ID: " B2_ACCOUNT_ID
-        read -r -s -p "Enter your B2 account key: " B2_ACCOUNT_KEY
+        read -r -p "Enter Restic repository: " RESTIC_REPOSITORY
+        read -r -p "Enter Restic password: " RESTIC_PASSWORD
+        read -r -p "Enter B2 account ID: " B2_ACCOUNT_ID
+        read -r -p "Enter B2 account key: " B2_ACCOUNT_KEY
     done
 }
 
+bootstrap_yay() {
+    sudo pacman --sync --noconfirm git base-devel
+    git clone https://aur.archlinux.org/yay.git
+    (cd yay && makepkg --syncdeps --install --noconfirm)
+    rm -rf yay
+}
+
+restore_from_restic() {
+    :
+}
+
 setup_wsl() {
-    echo "Hello from wsl"
+    sudo pacman --sync --refresh --upgrades --noconfirm
+    bootstrap_yay
+    yay --sync --noconfirm - < <(curl --silent --show-error --location \
+        https://raw.githubusercontent.com/jb49088/setup_script/master/packages/wsl/yay.txt)
+    restore_from_restic
 }
 
 setup_pi() {
@@ -31,6 +49,9 @@ setup_pi() {
 }
 
 main() {
+    sudo --validate
+    choose_machine
+    bootstrap_secrets
     case "$MACHINE" in
         wsl) setup_wsl ;;
         pi) setup_pi ;;
