chore: move function

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -16,21 +16,6 @@ select_machine() {
     done
 }
 
-prompt_for_secrets() {
-    export RESTIC_REPOSITORY RESTIC_PASSWORD B2_ACCOUNT_ID B2_ACCOUNT_KEY
-
-    while true; do
-        read -r -p "Enter Restic repository: " RESTIC_REPOSITORY
-        read -r -p "Enter Restic password: " RESTIC_PASSWORD
-        read -r -p "Enter B2 account ID: " B2_ACCOUNT_ID
-        read -r -p "Enter B2 account key: " B2_ACCOUNT_KEY
-
-        restic snapshots &>/dev/null && return
-
-        echo "Invalid credentials" >&2
-    done
-}
-
 bootstrap_yay() {
     sudo pacman -S --noconfirm git base-devel
     git clone https://aur.archlinux.org/yay.git
@@ -64,6 +49,21 @@ update_system() {
         wsl) sudo pacman -Syu --noconfirm ;;
         pi) sudo apt update && sudo apt upgrade --yes ;;
     esac
+}
+
+prompt_for_secrets() {
+    export RESTIC_REPOSITORY RESTIC_PASSWORD B2_ACCOUNT_ID B2_ACCOUNT_KEY
+
+    while true; do
+        read -r -p "Enter Restic repository: " RESTIC_REPOSITORY
+        read -r -p "Enter Restic password: " RESTIC_PASSWORD
+        read -r -p "Enter B2 account ID: " B2_ACCOUNT_ID
+        read -r -p "Enter B2 account key: " B2_ACCOUNT_KEY
+
+        restic snapshots &>/dev/null && return
+
+        echo "Invalid credentials" >&2
+    done
 }
 
 restore_from_restic() {
